name: 'Detox CI Tests'
on: [push]

jobs:
  tests:
    name: 'Running tests'
    runs-on: 'macOS-latest'
    steps:
      - name: Setup - Install Homebrew
        run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - name: Setup - Install Node
        run: brew install -f node
      - name: Setup - Install React Native CLI
        run: npm install -g react-native-cli
      - name: Setup - Install NPM Dependencies
        run: yarn
      - name: Setup - Install CocoaPods CLI
        run: sudo gem install cocoapods
      - name: Setup - Verify
        run: ./bin/setup
      - name: Run tests
        run: yarn ci:test
